/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payment;

import adminPanelAndMainFrame.FirstFrame;
import static databaseStuffs.DatabaseMethods.con;
import static databaseStuffs.DatabaseMethods.connectDB;
import static databaseStuffs.DatabaseMethods.resultSet;
import static databaseStuffs.DatabaseMethods.statement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import screenshot.GetScreenShot;
import screenshot.WriteLog;

/**
 *
 * @author Sirat
 */
public class PayRent extends javax.swing.JFrame {

    String date;
    private int gotBillIdFromDb;
    private int gotPayementIdFromDb;
    int totalBill;
    String rentId,shopName,month,year,bill,rent,total;

    /**
     * Creates new form PayRent
     */
    public PayRent() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        ImageIcon icon=new ImageIcon("Image/logo.png");
        setIconImage(icon.getImage());
        setTitle("Shopping Mall Management System");
        payButton.setVisible(false);
        addButton2.setVisible(false);//after adding bill it will be enable

        //Putting Current Date
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDate localDate = LocalDate.now();
        date = dtf.format(localDate);
        dateLabel.setText("Date: " + date);

        //Putting Bill Id and Payement Id
        try {
            connectDB();
            statement = con.createStatement();
            resultSet = statement.executeQuery("select bill_id from bill order by bill_id");
            while (resultSet.next()) {
                gotBillIdFromDb = resultSet.getInt(1);
            }
            billIdField.setText("" + (gotBillIdFromDb + 1));
            
            
            
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Can not generate Bill id");
        }
        connectDB();
        try {
            statement = con.createStatement();
            resultSet = statement.executeQuery("select rent_id, shop_name from rent");

            while (resultSet.next()) {
                 rentId = resultSet.getString(1);
                shopName = resultSet.getString(2);
                rentIdComboBox.addItem("(" + rentId + ") - " + shopName);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        electricityBillField = new javax.swing.JTextField();
        electricityBillLabel = new javax.swing.JLabel();
        gasBillLabel = new javax.swing.JLabel();
        gasBillField = new javax.swing.JTextField();
        otherBillLabel = new javax.swing.JLabel();
        otherBillField = new javax.swing.JTextField();
        addBillsLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        billIdLabel = new javax.swing.JLabel();
        billIdField = new javax.swing.JTextField();
        payementIdLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        payementIdField = new javax.swing.JTextField();
        monthsLabel = new javax.swing.JLabel();
        monthChoserComboBox = new javax.swing.JComboBox();
        yearLabel = new javax.swing.JLabel();
        yearChoserField = new javax.swing.JTextField();
        rentIdLabel = new javax.swing.JLabel();
        rentLabel = new javax.swing.JLabel();
        rentField = new javax.swing.JTextField();
        totalBillLabel = new javax.swing.JLabel();
        totalBillField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();
        addButton2 = new javax.swing.JButton();
        iconLabel = new javax.swing.JLabel();
        electricityBillLabel1 = new javax.swing.JLabel();
        gasBillLabel1 = new javax.swing.JLabel();
        otherBillLabel1 = new javax.swing.JLabel();
        addBillsLabel1 = new javax.swing.JLabel();
        billIdLabel1 = new javax.swing.JLabel();
        payementIdLabel1 = new javax.swing.JLabel();
        yearLabel1 = new javax.swing.JLabel();
        rentLabel1 = new javax.swing.JLabel();
        totalBillLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dateLabel1 = new javax.swing.JLabel();
        monthsLabel1 = new javax.swing.JLabel();
        rentIdComboBox = new javax.swing.JComboBox();
        setButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        backMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 450));
        getContentPane().setLayout(null);
        getContentPane().add(electricityBillField);
        electricityBillField.setBounds(140, 70, 90, 30);

        electricityBillLabel.setText("Electricity bill:");
        getContentPane().add(electricityBillLabel);
        electricityBillLabel.setBounds(20, 80, 100, 14);

        gasBillLabel.setText("Gas bill:");
        getContentPane().add(gasBillLabel);
        gasBillLabel.setBounds(20, 110, 90, 14);
        getContentPane().add(gasBillField);
        gasBillField.setBounds(140, 100, 90, 30);

        otherBillLabel.setText("Other bill:");
        getContentPane().add(otherBillLabel);
        otherBillLabel.setBounds(20, 140, 100, 14);
        getContentPane().add(otherBillField);
        otherBillField.setBounds(140, 130, 90, 30);

        addBillsLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        addBillsLabel.setText("Add Bills :");
        getContentPane().add(addBillsLabel);
        addBillsLabel.setBounds(10, 10, 210, 30);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(140, 163, 90, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(240, 10, 20, 180);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 202, 230, 10);

        billIdLabel.setText("Bill ID:");
        getContentPane().add(billIdLabel);
        billIdLabel.setBounds(20, 50, 70, 14);

        billIdField.setEditable(false);
        getContentPane().add(billIdField);
        billIdField.setBounds(140, 40, 90, 30);

        payementIdLabel.setText("Payement ID:");
        getContentPane().add(payementIdLabel);
        payementIdLabel.setBounds(270, 30, 100, 20);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(250, 10, 10, 230);

        payementIdField.setEditable(false);
        payementIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payementIdFieldActionPerformed(evt);
            }
        });
        getContentPane().add(payementIdField);
        payementIdField.setBounds(400, 30, 110, 30);

        monthsLabel.setText("Month:");
        getContentPane().add(monthsLabel);
        monthsLabel.setBounds(270, 80, 90, 20);

        monthChoserComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April","May","June","July","August","September","October","November","December" }));
        getContentPane().add(monthChoserComboBox);
        monthChoserComboBox.setBounds(400, 80, 110, 30);

        yearLabel.setText("Year:");
        getContentPane().add(yearLabel);
        yearLabel.setBounds(270, 124, 90, 20);
        getContentPane().add(yearChoserField);
        yearChoserField.setBounds(400, 120, 110, 30);

        rentIdLabel.setText("Rent ID:");
        getContentPane().add(rentIdLabel);
        rentIdLabel.setBounds(270, 170, 70, 30);

        rentLabel.setText("Rent:");
        getContentPane().add(rentLabel);
        rentLabel.setBounds(270, 224, 80, 20);
        getContentPane().add(rentField);
        rentField.setBounds(400, 220, 110, 30);

        totalBillLabel.setText("Total Bill:");
        getContentPane().add(totalBillLabel);
        totalBillLabel.setBounds(20, 220, 110, 30);
        getContentPane().add(totalBillField);
        totalBillField.setBounds(130, 220, 100, 30);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(70, 262, 440, 10);

        jLabel12.setText("Total:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 274, 70, 20);
        getContentPane().add(totalField);
        totalField.setBounds(110, 270, 260, 30);

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateLabel.setText("Date");
        getContentPane().add(dateLabel);
        dateLabel.setBounds(440, 270, 200, 30);

        payButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });
        getContentPane().add(payButton);
        payButton.setBounds(200, 310, 230, 50);

        addButton2.setText("Add");
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(addButton2);
        addButton2.setBounds(520, 220, 60, 30);
        getContentPane().add(iconLabel);
        iconLabel.setBounds(520, 380, 110, 40);

        electricityBillLabel1.setText("Electricity bill:");
        getContentPane().add(electricityBillLabel1);
        electricityBillLabel1.setBounds(20, 80, 100, 14);

        gasBillLabel1.setText("Gas bill:");
        getContentPane().add(gasBillLabel1);
        gasBillLabel1.setBounds(20, 110, 90, 14);

        otherBillLabel1.setText("Other bill:");
        getContentPane().add(otherBillLabel1);
        otherBillLabel1.setBounds(20, 140, 100, 14);

        addBillsLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        addBillsLabel1.setText("Add Bills :");
        getContentPane().add(addBillsLabel1);
        addBillsLabel1.setBounds(10, 10, 210, 30);

        billIdLabel1.setText("Bill ID:");
        getContentPane().add(billIdLabel1);
        billIdLabel1.setBounds(20, 50, 70, 14);

        payementIdLabel1.setText("Payement ID:");
        getContentPane().add(payementIdLabel1);
        payementIdLabel1.setBounds(270, 30, 100, 20);

        yearLabel1.setText("Year:");
        getContentPane().add(yearLabel1);
        yearLabel1.setBounds(270, 124, 90, 20);

        rentLabel1.setText("Rent:");
        getContentPane().add(rentLabel1);
        rentLabel1.setBounds(270, 224, 80, 20);

        totalBillLabel1.setText("Total Bill:");
        getContentPane().add(totalBillLabel1);
        totalBillLabel1.setBounds(20, 220, 110, 30);

        jLabel13.setText("Total:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 274, 70, 20);

        dateLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateLabel1.setText("Date");
        getContentPane().add(dateLabel1);
        dateLabel1.setBounds(440, 270, 200, 30);

        monthsLabel1.setForeground(new java.awt.Color(204, 204, 204));
        monthsLabel1.setText("Month:");
        getContentPane().add(monthsLabel1);
        monthsLabel1.setBounds(270, 80, 90, 20);

        rentIdComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        rentIdComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rentIdComboBoxItemStateChanged(evt);
            }
        });
        getContentPane().add(rentIdComboBox);
        rentIdComboBox.setBounds(320, 170, 250, 30);

        setButton.setText("Set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });
        getContentPane().add(setButton);
        setButton.setBounds(570, 170, 60, 30);

        homeMenu.setText("Home");
        homeMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                homeMenuMenuSelected(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        backMenu.setText("Back");
        backMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                backMenuMenuSelected(evt);
            }
        });
        jMenuBar1.add(backMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payementIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payementIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payementIdFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            String billId = billIdField.getText();
            String electricityBill = electricityBillField.getText();
            String gasBill = gasBillField.getText();
            String otherBill = otherBillField.getText();

            String sql = "INSERT INTO `shopping_mall_database`.`bill` (`bill_id`, `electricity_bill`, `other_bill`, `gas_bill`) VALUES ('" + billId + "'," + electricityBill + ", '" + otherBill + "', '" + gasBill + "')";
            statement.executeUpdate(sql);
            addButton2.setVisible(true);
            totalBill = Integer.parseInt(gasBill) + Integer.parseInt(electricityBill) + Integer.parseInt(otherBill);
            totalBillField.setText("" + totalBill);

            //Putting Payment Id
            try {
                connectDB();
                statement = con.createStatement();
                resultSet = statement.executeQuery("select payment_id from payment order by payment_id");
                while (resultSet.next()) {
                    gotPayementIdFromDb = resultSet.getInt(1);
                }
                payementIdField.setText("" + (gotPayementIdFromDb + 1));
            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "Can not generate Payement id");
            }
            //Genereted

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Something Wrong");
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        String rent = rentField.getText();
        int total = totalBill + Integer.parseInt(rent);
        totalField.setText("" + total);
        payButton.setVisible(true);
        addButton2.setVisible(false);
    }//GEN-LAST:event_addButton2ActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        String billId = billIdField.getText();
        String paymentId = payementIdField.getText();
        int month = monthChoserComboBox.getSelectedIndex() + 1;
        String year = yearChoserField.getText();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate localDate = LocalDate.now();
        date = dtf.format(localDate);
        
        String comboText = rentIdComboBox.getSelectedItem().toString(); // getting id from comboBox
        String comboText2[] = comboText.split("-");
        String rentId = comboText2[0].replaceAll("\\D+", "");
        
        
        String rent = rentField.getText();
        System.out.println(month);

        try {
            String sql = "INSERT INTO `shopping_mall_database`.`payment` (`payment_id`, `month`, `year`, `rent`, `paying_date`, `rent_id`, `bill_id`) VALUES "
                    + "('" + paymentId + "', '" + month + "', '" + year + "', '" + rent + "', '" + date + "', '" + rentId + "', '" + billId + "')";
            
            
           
            this.month=""+month;
            this.year=""+year;
            this.bill=totalBillField.getText();
            this.rent=rentField.getText();
            this.total=totalField.getText();
            
            
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Payment Successful");
            
            new Receipt(this.rentId, this.shopName, this.month, this.year, this.bill, this.rent, this.total);
            new WriteLog("New Payment Done On  ID ="+paymentId+" .");
            new GetScreenShot(this,"payment_ID_"+paymentId);
            FirstFrame ob = new FirstFrame();
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Something Wrong");

        }


    }//GEN-LAST:event_payButtonActionPerformed

    private void backMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_backMenuMenuSelected

        PaymentHome ob = new PaymentHome();
        this.dispose();
    }//GEN-LAST:event_backMenuMenuSelected

    private void homeMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_homeMenuMenuSelected
        FirstFrame ob = new FirstFrame();
        this.dispose();
    }//GEN-LAST:event_homeMenuMenuSelected

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
        // TODO add your handling code here:
        String comboText = rentIdComboBox.getSelectedItem().toString(); // getting id from comboBox
        String comboText2[] = comboText.split("-");
        String rentId = comboText2[0].replaceAll("\\D+", "");
        shopName=comboText2[1].trim();
        System.out.println(rentId);
        String shopId="";
        String shopRent="";
        
        
        try {
            connectDB();
            statement = con.createStatement();
            resultSet = statement.executeQuery("select shop_id from rent where rent_id = " + rentId);
            while (resultSet.next()) {
                shopId = resultSet.getString(1);
            }
            System.out.println("Shop id = "+shopId);
            statement = con.createStatement();
            resultSet = statement.executeQuery("select rent from shop where shop_id = " + shopId);
            while (resultSet.next()) {
                shopRent = resultSet.getString(1);
            }
            System.out.println("Shop shopRent = "+shopRent);
            rentField.setText(shopRent);
            
            
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Can not generate Bill id");
        }
        
        
        
    }//GEN-LAST:event_setButtonActionPerformed

    private void rentIdComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rentIdComboBoxItemStateChanged
       
    }//GEN-LAST:event_rentIdComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayRent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBillsLabel;
    private javax.swing.JLabel addBillsLabel1;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton2;
    private javax.swing.JMenu backMenu;
    private javax.swing.JTextField billIdField;
    private javax.swing.JLabel billIdLabel;
    private javax.swing.JLabel billIdLabel1;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateLabel1;
    private javax.swing.JTextField electricityBillField;
    private javax.swing.JLabel electricityBillLabel;
    private javax.swing.JLabel electricityBillLabel1;
    private javax.swing.JTextField gasBillField;
    private javax.swing.JLabel gasBillLabel;
    private javax.swing.JLabel gasBillLabel1;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox monthChoserComboBox;
    private javax.swing.JLabel monthsLabel;
    private javax.swing.JLabel monthsLabel1;
    private javax.swing.JTextField otherBillField;
    private javax.swing.JLabel otherBillLabel;
    private javax.swing.JLabel otherBillLabel1;
    private javax.swing.JButton payButton;
    private javax.swing.JTextField payementIdField;
    private javax.swing.JLabel payementIdLabel;
    private javax.swing.JLabel payementIdLabel1;
    private javax.swing.JTextField rentField;
    private javax.swing.JComboBox rentIdComboBox;
    private javax.swing.JLabel rentIdLabel;
    private javax.swing.JLabel rentLabel;
    private javax.swing.JLabel rentLabel1;
    private javax.swing.JButton setButton;
    private javax.swing.JTextField totalBillField;
    private javax.swing.JLabel totalBillLabel;
    private javax.swing.JLabel totalBillLabel1;
    private javax.swing.JTextField totalField;
    private javax.swing.JTextField yearChoserField;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JLabel yearLabel1;
    // End of variables declaration//GEN-END:variables
}
