/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payment;

import java.awt.Color;
import static java.awt.Component.TOP_ALIGNMENT;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Rahat
 */
public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    String date;
    JPanel jpp;
    public Receipt(String rentId,String shopName,String month,String year,String bill,String rent,String total) {
        initComponents();
         this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         ImageIcon icon=new ImageIcon("Image/logo.png");
        setIconImage(icon.getImage());
        setTitle("Shopping Mall Management System");
         //Putting Current Date
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDate localDate = LocalDate.now();
        date = dtf.format(localDate);
        dateLabel.setText("Date: " + date);
        
        rentIdLabel.setText("Deal ID : "+rentId);
        shopNameLabel.setText("Shop Name : "+shopName);
        monthLabel.setText("Month : "+month);
        yearLabel.setText("Year : "+year);
        billLabel1.setText("Bill : "+bill);
        rentlLabel.setText("Rent : "+rent);
        totallLabel.setText("Total : "+total);
        
        
        jpp=jPanel1;
        jPanel1.setBackground(Color.WHITE);
        this.setBackground(Color.WHITE);
        
        setVisible(true);
        print();
    }
    
    void print(){
        PrinterJob job= PrinterJob.getPrinterJob();
        job.setJobName("Hello print ");
        job.setPrintable(new Printable() {

            @Override
            public int print(Graphics g, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if(pageIndex>0)
                {
                    return (NO_SUCH_PAGE);
                }
                else{
                    Graphics2D g2d=(Graphics2D) g;
                    g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                    g2d.drawString("hiiii", TOP_ALIGNMENT, TOP_ALIGNMENT);
                    jpp.paint(g2d);
                    return (PAGE_EXISTS);
                }
                
                
                
              
            }
        });
        
        if(job.printDialog()){
            try{
                job.print( );
            }catch(PrinterException e){
                
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rentlLabel = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        rentIdLabel = new javax.swing.JLabel();
        shopNameLabel = new javax.swing.JLabel();
        billLabel1 = new javax.swing.JLabel();
        totallLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(445, 592));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateLabel.setText("Date");
        jPanel1.add(dateLabel);
        dateLabel.setBounds(268, 135, 149, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Payment Receipt");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(31, 130, 386, 41);

        rentlLabel.setText("jLabel2");
        jPanel1.add(rentlLabel);
        rentlLabel.setBounds(31, 414, 386, 35);

        monthLabel.setText("jLabel2");
        jPanel1.add(monthLabel);
        monthLabel.setBounds(31, 281, 386, 35);

        yearLabel.setText("jLabel2");
        jPanel1.add(yearLabel);
        yearLabel.setBounds(31, 327, 386, 35);

        rentIdLabel.setText("jLabel2");
        jPanel1.add(rentIdLabel);
        rentIdLabel.setBounds(31, 182, 386, 35);

        shopNameLabel.setText("jLabel2");
        jPanel1.add(shopNameLabel);
        shopNameLabel.setBounds(31, 228, 386, 35);

        billLabel1.setText("jLabel2");
        jPanel1.add(billLabel1);
        billLabel1.setBounds(31, 373, 386, 35);

        totallLabel.setText("tt");
        jPanel1.add(totallLabel);
        totallLabel.setBounds(31, 455, 386, 35);

        jLabel2.setText("Authority Signature");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(287, 508, 130, 22);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel3.setText("ABC Shopping Mall");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(21, 0, 396, 44);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Zindabazar Point, Sylhet 3100, Bangladesh");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(49, 50, 386, 17);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 78, 445, 10);

        logoLabel.setIcon(new javax.swing.ImageIcon("D:\\Final Project\\final project\\Shopping Mall Management System\\Image\\logoR.png")); // NOI18N
        jPanel1.add(logoLabel);
        logoLabel.setBounds(30, 120, 390, 390);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 445, 592);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        new Receipt("", "", "", "", "", "", "");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billLabel1;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel rentIdLabel;
    private javax.swing.JLabel rentlLabel;
    private javax.swing.JLabel shopNameLabel;
    private javax.swing.JLabel totallLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
