/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dealsAndPayments;

import adminPanelAndMainFrame.FirstFrame;
import static databaseStuffs.DatabaseMethods.con;
import static databaseStuffs.DatabaseMethods.connectDB;
import static databaseStuffs.DatabaseMethods.resultSet;
import static databaseStuffs.DatabaseMethods.statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import screenshot.GetScreenShot;
import screenshot.WriteLog;

/**
 *
 * @author Sirat
 */
public class DealFinal extends javax.swing.JFrame {

    int rentId;
    String shopId;
    String tenantId;
    int cameFrom;

    public DealFinal(String shopId, String tenantId , int cameFrom) {
        initComponents();
        this.cameFrom=cameFrom;
        ImageIcon icon=new ImageIcon("Image/logo.png");
        setIconImage(icon.getImage());
        setTitle("Shopping Mall Management System");
        this.shopId = shopId;
        this.tenantId = tenantId;
        setVisible(true);
        setLocationRelativeTo(null);

        try {
            connectDB();
            statement = con.createStatement();
            resultSet = statement.executeQuery("select rent_id from rent order by rent_id");
            while (resultSet.next()) {
                rentId = resultSet.getInt(1);
            }
            rentIdTextField.setText("" + (++rentId));
            tenantIdTextField.setText(tenantId);
            shopIdTextField.setText(shopId);
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Can not generate id");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rentIdLabel = new javax.swing.JLabel();
        shopIdLabel = new javax.swing.JLabel();
        tenantIdLabel = new javax.swing.JLabel();
        shopNameLabel = new javax.swing.JLabel();
        rentIdTextField = new javax.swing.JTextField();
        shopIdTextField = new javax.swing.JTextField();
        tenantIdTextField = new javax.swing.JTextField();
        shopNameTextField = new javax.swing.JTextField();
        dealFinalButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        backMenu = new javax.swing.JMenu();
        homeMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        rentIdLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        rentIdLabel.setText("Rent ID: ");
        getContentPane().add(rentIdLabel);
        rentIdLabel.setBounds(10, 11, 102, 19);

        shopIdLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        shopIdLabel.setText("Shop ID: ");
        getContentPane().add(shopIdLabel);
        shopIdLabel.setBounds(10, 49, 102, 19);

        tenantIdLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        tenantIdLabel.setText("Tenant ID: ");
        getContentPane().add(tenantIdLabel);
        tenantIdLabel.setBounds(10, 87, 102, 19);

        shopNameLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        shopNameLabel.setText("Enter a Shop Name :");
        getContentPane().add(shopNameLabel);
        shopNameLabel.setBounds(10, 125, 180, 19);

        rentIdTextField.setEditable(false);
        getContentPane().add(rentIdTextField);
        rentIdTextField.setBounds(120, 10, 74, 30);

        shopIdTextField.setEditable(false);
        shopIdTextField.setText(" ");
        getContentPane().add(shopIdTextField);
        shopIdTextField.setBounds(120, 50, 74, 30);

        tenantIdTextField.setEditable(false);
        tenantIdTextField.setText(" ");
        getContentPane().add(tenantIdTextField);
        tenantIdTextField.setBounds(120, 90, 74, 30);

        shopNameTextField.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        getContentPane().add(shopNameTextField);
        shopNameTextField.setBounds(10, 155, 400, 49);

        dealFinalButton.setText("Deal Final");
        dealFinalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealFinalButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dealFinalButton);
        dealFinalButton.setBounds(150, 210, 130, 31);

        backMenu.setText("Back");
        backMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                backMenuMenuSelected(evt);
            }
        });
        jMenuBar1.add(backMenu);

        homeMenu.setText("Home");
        homeMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                homeMenuMenuSelected(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dealFinalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealFinalButtonActionPerformed
        String shopName = shopNameTextField.getText();
        String sql = "INSERT INTO `shopping_mall_database`.`rent` (`rent_id`, `shop_name`, `shop_id`, `tenant_id`) VALUES ('"
                + rentId + "', '" + shopName + "', '" + shopId + "', '" + tenantId + "')";
        try {
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Rent Added");
            new WriteLog("Rent ID ="+rentId+" Added.");
            new GetScreenShot(this,"deal_ID_"+rentId);
            FirstFrame ob = new FirstFrame();
            this.dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Something Wrong");
        }


    }//GEN-LAST:event_dealFinalButtonActionPerformed

    private void homeMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_homeMenuMenuSelected
        new FirstFrame();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homeMenuMenuSelected

    private void backMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_backMenuMenuSelected
        if(this.cameFrom==1)
        {
            new RentDeal();
        this.dispose();
        }
        else if (this.cameFrom==2){
            new RentDealFromShop(shopId);
        this.dispose();
        }
    }//GEN-LAST:event_backMenuMenuSelected



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu backMenu;
    private javax.swing.JButton dealFinalButton;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel rentIdLabel;
    private javax.swing.JTextField rentIdTextField;
    private javax.swing.JLabel shopIdLabel;
    private javax.swing.JTextField shopIdTextField;
    private javax.swing.JLabel shopNameLabel;
    private javax.swing.JTextField shopNameTextField;
    private javax.swing.JLabel tenantIdLabel;
    private javax.swing.JTextField tenantIdTextField;
    // End of variables declaration//GEN-END:variables
}
