/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dealsAndPayments;

import adminPanelAndMainFrame.FirstFrame;
import static databaseStuffs.DatabaseMethods.con;
import static databaseStuffs.DatabaseMethods.connectDB;
import static databaseStuffs.DatabaseMethods.resultSet;
import static databaseStuffs.DatabaseMethods.resultSet2;
import static databaseStuffs.DatabaseMethods.statement;
import static databaseStuffs.DatabaseMethods.statement2;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sirat
 */
public class RentDeal extends javax.swing.JFrame {

    String shopId = "";
    String tenantId = "";
    int counter = 0;
    DefaultTableModel model;

    /**
     * Creates new form rentDeal
     */
    public RentDeal() {
        initComponents();
        ImageIcon icon = new ImageIcon("Image/logo.png");
        setIconImage(icon.getImage());
        setTitle("Shopping Mall Management System");
        model = (DefaultTableModel) availableShopTable.getModel();

        connectDB();
        try {
            statement = con.createStatement();
            resultSet = statement.executeQuery("select shop_id,room_no,floor from shop");
            int serial = 1;
            while (resultSet.next()) {
                String shopID = resultSet.getString(1);
                String roomNo = resultSet.getString(2);
                String floorNo = resultSet.getString(3);
                String availablity = "";

                statement2 = con.createStatement();
                resultSet2 = statement2.executeQuery("select rent_id from rent where shop_id=" + shopID);
                while (resultSet2.next()) {
                    availablity = resultSet2.getString(1);
                }
                if (availablity.isEmpty() || availablity == null || availablity == "") {
                    model.addRow(new Object[]{serial, shopID, roomNo, floorNo});
                    serial++;
                }

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        
        
        model = (DefaultTableModel) availableTenantTable.getModel();

        try {
            statement = con.createStatement();
            resultSet = statement.executeQuery("select tenant_id,name,occupation from tenant");
            int serial = 1;
            while (resultSet.next()) {
                String tenantId = resultSet.getString(1);
                String tenantName = resultSet.getString(2);
                String tenantOccupation = resultSet.getString(3);
                String availablity = "";

                statement2 = con.createStatement();
                resultSet2 = statement2.executeQuery("select rent_id from rent where tenant_id=" + tenantId);
                while (resultSet2.next()) {

                    availablity = resultSet2.getString(1);

                }
                if (availablity.isEmpty() || availablity == null || availablity == "") {
                    model.addRow(new Object[]{serial, tenantId, tenantName, tenantOccupation});
                serial++;
                } 
                
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }


        this.setLocationRelativeTo(null);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dealButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableShopTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        availableTenantTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rent Deal");
        setMinimumSize(new java.awt.Dimension(500, 380));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Select Shop: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 30, 100, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Select Tenant:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 140, 90, 20);

        dealButton.setBackground(new java.awt.Color(204, 204, 255));
        dealButton.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        dealButton.setForeground(new java.awt.Color(0, 0, 102));
        dealButton.setText("Deal");
        dealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dealButton);
        dealButton.setBounds(180, 240, 130, 60);

        availableShopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "ID", "Room No", "Floor"
            }
        ));
        jScrollPane1.setViewportView(availableShopTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 10, 380, 90);

        availableTenantTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "ID", "Name", "Occupation"
            }
        ));
        jScrollPane2.setViewportView(availableTenantTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(102, 110, 380, 90);

        homeMenu.setText("Home");
        homeMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                homeMenuMenuSelected(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_homeMenuMenuSelected
        new FirstFrame();
        this.dispose();
    }//GEN-LAST:event_homeMenuMenuSelected

    private void dealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealButtonActionPerformed
        
        String finalShopId="",finalTenantID="";

        int rawNumber = -1;
        rawNumber = availableShopTable.getSelectedRow();
        //   System.out.println(rawNumber);
        if (rawNumber < 0) {
            JOptionPane.showMessageDialog(this, "Select a Available Shop");
        } else {
            finalShopId = (String) availableShopTable.getModel().getValueAt(rawNumber, 1);
        }
       
         rawNumber = -1;
        rawNumber = availableTenantTable.getSelectedRow();
        //   System.out.println(rawNumber);
        if (rawNumber < 0) {
            JOptionPane.showMessageDialog(this, "Select a Available Tenant");
        } else {
            finalTenantID = (String) availableTenantTable.getModel().getValueAt(rawNumber, 1);
        }
        
        
        if(!finalShopId.isEmpty() && !finalTenantID.isEmpty() && finalShopId!=null && finalTenantID!=null)
        {
            new DealFinal(finalShopId, finalTenantID,1);
             this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Select a Available Shop and Tenant");
        }
        
        

    }//GEN-LAST:event_dealButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentDeal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable availableShopTable;
    private javax.swing.JTable availableTenantTable;
    private javax.swing.JButton dealButton;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
