package adminPanelAndMainFrame;

import dealsAndPayments.*;
import javax.swing.ImageIcon;
import payment.*;
import shop.*;
import referencePeople.*;
import tenant.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sirat
 */
public class FirstFrame extends javax.swing.JFrame {

    /**
     * Creates new form FirstFrame
     */
    public FirstFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon icon=new ImageIcon("Image/logo.png");
        setIconImage(icon.getImage());
        setTitle("Shopping Mall Management System");
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        addShopButton = new javax.swing.JButton();
        addRefButton = new javax.swing.JButton();
        addTenantButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        viewShopButton = new javax.swing.JButton();
        viewRefButton = new javax.swing.JButton();
        viewTenantButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        editShopButton = new javax.swing.JButton();
        editRefButton = new javax.swing.JButton();
        editTenantButton = new javax.swing.JButton();
        rentAShopButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        paymentMenuItem = new javax.swing.JMenuItem();
        viewDealMenuItem = new javax.swing.JMenuItem();
        logMenuItem = new javax.swing.JMenuItem();
        optionMenu = new javax.swing.JMenu();
        settingMenuItem = new javax.swing.JMenuItem();
        deleteMenu = new javax.swing.JMenu();
        deletePaymentMenuItem = new javax.swing.JMenuItem();
        deleteRentMenuItem = new javax.swing.JMenuItem();
        deleteShopMenuItem = new javax.swing.JMenuItem();
        deleteTenantMenuItem = new javax.swing.JMenuItem();
        deleteReferenceMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        contractUsMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setMinimumSize(new java.awt.Dimension(600, 450));
        setName("FirstFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        addShopButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addShopButton.setText("Add Shop");
        addShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShopButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addShopButton);
        addShopButton.setBounds(30, 20, 140, 50);

        addRefButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addRefButton.setText("Add Ref");
        addRefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRefButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addRefButton);
        addRefButton.setBounds(30, 100, 140, 50);

        addTenantButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addTenantButton.setText("Add Tenant");
        addTenantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTenantButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addTenantButton);
        addTenantButton.setBounds(30, 180, 140, 50);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(200, 0, 10, 230);

        viewShopButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewShopButton.setText("View Shop");
        viewShopButton.setMaximumSize(new java.awt.Dimension(101, 23));
        viewShopButton.setMinimumSize(new java.awt.Dimension(101, 23));
        viewShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewShopButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewShopButton);
        viewShopButton.setBounds(230, 20, 140, 50);

        viewRefButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewRefButton.setText("View Ref");
        viewRefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRefButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewRefButton);
        viewRefButton.setBounds(230, 100, 140, 50);

        viewTenantButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewTenantButton.setText("View Tenant");
        viewTenantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTenantButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewTenantButton);
        viewTenantButton.setBounds(230, 180, 140, 50);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(390, 0, 10, 230);

        editShopButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editShopButton.setText("Edit Shop");
        editShopButton.setMaximumSize(new java.awt.Dimension(101, 23));
        editShopButton.setMinimumSize(new java.awt.Dimension(101, 23));
        editShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editShopButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editShopButton);
        editShopButton.setBounds(430, 20, 140, 50);

        editRefButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editRefButton.setText("Edit Ref");
        editRefButton.setMaximumSize(new java.awt.Dimension(101, 23));
        editRefButton.setMinimumSize(new java.awt.Dimension(101, 23));
        editRefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRefButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editRefButton);
        editRefButton.setBounds(430, 100, 140, 50);

        editTenantButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editTenantButton.setText("Edit Tenant");
        editTenantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTenantButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editTenantButton);
        editTenantButton.setBounds(430, 180, 140, 50);

        rentAShopButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        rentAShopButton.setText("Deal For A Shop");
        rentAShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentAShopButtonActionPerformed(evt);
            }
        });
        getContentPane().add(rentAShopButton);
        rentAShopButton.setBounds(150, 290, 310, 80);

        logoutButton.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton);
        logoutButton.setBounds(10, 350, 90, 21);

        fileMenu.setText("File");

        paymentMenuItem.setText("Payment");
        paymentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(paymentMenuItem);

        viewDealMenuItem.setText("View Deals");
        viewDealMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDealMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(viewDealMenuItem);

        logMenuItem.setText("View Log");
        logMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(logMenuItem);

        menuBar.add(fileMenu);

        optionMenu.setText("Option");
        optionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionMenuActionPerformed(evt);
            }
        });

        settingMenuItem.setText("Setting");
        settingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingMenuItemActionPerformed(evt);
            }
        });
        optionMenu.add(settingMenuItem);

        menuBar.add(optionMenu);

        deleteMenu.setText("Delete");

        deletePaymentMenuItem.setText("Payment Information");
        deletePaymentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePaymentMenuItemActionPerformed(evt);
            }
        });
        deleteMenu.add(deletePaymentMenuItem);

        deleteRentMenuItem.setText("Rent Deal");
        deleteRentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRentMenuItemActionPerformed(evt);
            }
        });
        deleteMenu.add(deleteRentMenuItem);

        deleteShopMenuItem.setText("Shop");
        deleteShopMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteShopMenuItemActionPerformed(evt);
            }
        });
        deleteMenu.add(deleteShopMenuItem);

        deleteTenantMenuItem.setText("Tenant");
        deleteTenantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTenantMenuItemActionPerformed(evt);
            }
        });
        deleteMenu.add(deleteTenantMenuItem);

        deleteReferenceMenuItem.setText("Referenced People");
        deleteReferenceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteReferenceMenuItemActionPerformed(evt);
            }
        });
        deleteMenu.add(deleteReferenceMenuItem);

        menuBar.add(deleteMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        contractUsMenuItem.setText("Contract Us");
        contractUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractUsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contractUsMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShopButtonActionPerformed
        AddShop object = new AddShop();
        this.dispose();
    }//GEN-LAST:event_addShopButtonActionPerformed

    private void viewShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewShopButtonActionPerformed
        PreViewShop object = new PreViewShop();
        this.dispose();
    }//GEN-LAST:event_viewShopButtonActionPerformed

    private void editShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editShopButtonActionPerformed
        PreEditShop object = new PreEditShop();
        this.dispose();
    }//GEN-LAST:event_editShopButtonActionPerformed

    private void addRefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRefButtonActionPerformed
        AddReference object = new AddReference();
        this.dispose();
    }//GEN-LAST:event_addRefButtonActionPerformed

    private void viewRefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRefButtonActionPerformed
        PreViewRef object = new PreViewRef();
        this.dispose();
    }//GEN-LAST:event_viewRefButtonActionPerformed

    private void editRefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRefButtonActionPerformed
        PreEditRef object = new PreEditRef();
        this.dispose();
    }//GEN-LAST:event_editRefButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LogIn LogInObject = new LogIn();
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void optionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionMenuActionPerformed

    }//GEN-LAST:event_optionMenuActionPerformed

    private void settingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingMenuItemActionPerformed
        Setting ob = new Setting();
        this.dispose();
    }//GEN-LAST:event_settingMenuItemActionPerformed

    private void addTenantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTenantButtonActionPerformed
        new AddTenant();
        this.dispose();
    }//GEN-LAST:event_addTenantButtonActionPerformed

    private void viewTenantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTenantButtonActionPerformed
        new PreViewTenant();
        this.dispose();
    }//GEN-LAST:event_viewTenantButtonActionPerformed

    private void editTenantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTenantButtonActionPerformed
        new PreEditTenant();
        this.dispose();
    }//GEN-LAST:event_editTenantButtonActionPerformed

    private void rentAShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentAShopButtonActionPerformed
        new RentDeal();
        this.dispose();
    }//GEN-LAST:event_rentAShopButtonActionPerformed

    private void deleteRentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRentMenuItemActionPerformed
        new DeleteDeal();
        this.dispose();
    }//GEN-LAST:event_deleteRentMenuItemActionPerformed

    private void deleteShopMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteShopMenuItemActionPerformed
        new DeleteShop();
        this.dispose();
    }//GEN-LAST:event_deleteShopMenuItemActionPerformed

    private void deleteReferenceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteReferenceMenuItemActionPerformed
        new DeleteReference();
        this.dispose();
    }//GEN-LAST:event_deleteReferenceMenuItemActionPerformed

    private void deleteTenantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTenantMenuItemActionPerformed
        new DeleteTenant();
        this.dispose();
    }//GEN-LAST:event_deleteTenantMenuItemActionPerformed

    private void paymentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentMenuItemActionPerformed

        new PaymentHome();
        this.dispose();
    }//GEN-LAST:event_paymentMenuItemActionPerformed

    private void deletePaymentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePaymentMenuItemActionPerformed
        new DeletePayment();
        this.dispose();
    }//GEN-LAST:event_deletePaymentMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new About();
        this.dispose();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void contractUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractUsMenuItemActionPerformed
        new Contract();
        this.dispose();
    }//GEN-LAST:event_contractUsMenuItemActionPerformed

    private void viewDealMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDealMenuItemActionPerformed
        // TODO add your handling code here:
        new viewDeal();
        this.dispose();
    }//GEN-LAST:event_viewDealMenuItemActionPerformed

    private void logMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logMenuItemActionPerformed
        // TODO add your handling code here:
        new ViewLog();
        this.dispose();
    }//GEN-LAST:event_logMenuItemActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstFrame().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton addRefButton;
    private javax.swing.JButton addShopButton;
    private javax.swing.JButton addTenantButton;
    private javax.swing.JMenuItem contractUsMenuItem;
    private javax.swing.JMenu deleteMenu;
    private javax.swing.JMenuItem deletePaymentMenuItem;
    private javax.swing.JMenuItem deleteReferenceMenuItem;
    private javax.swing.JMenuItem deleteRentMenuItem;
    private javax.swing.JMenuItem deleteShopMenuItem;
    private javax.swing.JMenuItem deleteTenantMenuItem;
    private javax.swing.JButton editRefButton;
    private javax.swing.JButton editShopButton;
    private javax.swing.JButton editTenantButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem logMenuItem;
    private javax.swing.JButton logoutButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu optionMenu;
    private javax.swing.JMenuItem paymentMenuItem;
    private javax.swing.JButton rentAShopButton;
    private javax.swing.JMenuItem settingMenuItem;
    private javax.swing.JMenuItem viewDealMenuItem;
    private javax.swing.JButton viewRefButton;
    private javax.swing.JButton viewShopButton;
    private javax.swing.JButton viewTenantButton;
    // End of variables declaration//GEN-END:variables
}
