package adminPanelAndMainFrame;

import static databaseStuffs.DatabaseMethods.con;
import static databaseStuffs.DatabaseMethods.connectDB;
import static databaseStuffs.DatabaseMethods.resultSet;
import static databaseStuffs.DatabaseMethods.statement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sirat
 */
public class Setting extends javax.swing.JFrame {

    /**
     * Creates new form Setting
     */
    public Setting() {
        initComponents();
        ImageIcon icon = new ImageIcon("Image/logo.png");
        setIconImage(icon.getImage());
         icon = new ImageIcon("Image/backup.png");
         backupButton.setIcon(icon);
        
        setTitle("Shopping Mall Management System");

        try {
            connectDB();
            String screenshotStatus = "";

            statement = con.createStatement();
            resultSet = statement.executeQuery("select status from screenshot");
            while (resultSet.next()) {
                screenshotStatus = resultSet.getString(1);

            }
            if (screenshotStatus.matches("0")) {
                offButton.setEnabled(false);
            } else {
                onButton.setEnabled(false);
            }

        } catch (SQLException ex) {

        }

        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNewUserButton = new javax.swing.JButton();
        changeUsernamePasswordButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        onButton = new javax.swing.JButton();
        offButton = new javax.swing.JButton();
        backupButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        backMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        addNewUserButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addNewUserButton.setForeground(new java.awt.Color(51, 51, 51));
        addNewUserButton.setText("Add New User");
        addNewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addNewUserButton);
        addNewUserButton.setBounds(70, 100, 267, 53);

        changeUsernamePasswordButton.setBackground(new java.awt.Color(255, 204, 0));
        changeUsernamePasswordButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        changeUsernamePasswordButton.setForeground(new java.awt.Color(51, 51, 51));
        changeUsernamePasswordButton.setText("Update User Security");
        changeUsernamePasswordButton.setMaximumSize(new java.awt.Dimension(131, 25));
        changeUsernamePasswordButton.setMinimumSize(new java.awt.Dimension(131, 25));
        changeUsernamePasswordButton.setPreferredSize(new java.awt.Dimension(131, 25));
        changeUsernamePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUsernamePasswordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(changeUsernamePasswordButton);
        changeUsernamePasswordButton.setBounds(70, 40, 270, 58);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("  Warning: Deleting Account could be Dangerous ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 160, 270, 14);

        jLabel2.setText("Take Screenshot :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 190, 110, 20);

        onButton.setText("On");
        onButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonActionPerformed(evt);
            }
        });
        getContentPane().add(onButton);
        onButton.setBounds(170, 190, 73, 23);

        offButton.setText("OFF");
        offButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offButtonActionPerformed(evt);
            }
        });
        getContentPane().add(offButton);
        offButton.setBounds(260, 190, 70, 23);

        backupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backupButton);
        backupButton.setBounds(350, 0, 40, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("BACKUP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 40, 50, 14);

        backMenu.setText("Back");
        backMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                backMenuMenuSelected(evt);
            }
        });
        backMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(backMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuActionPerformed
        FirstFrame FirstFrameObject = new FirstFrame();
        this.dispose();
    }//GEN-LAST:event_backMenuActionPerformed

    private void changeUsernamePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUsernamePasswordButtonActionPerformed
        Setting_ChangeUsernamePassword ob = new Setting_ChangeUsernamePassword();
        this.dispose();
    }//GEN-LAST:event_changeUsernamePasswordButtonActionPerformed

    private void addNewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewUserButtonActionPerformed
        Setting_AddNewUser ob = new Setting_AddNewUser();
        this.dispose();
    }//GEN-LAST:event_addNewUserButtonActionPerformed

    private void backMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_backMenuMenuSelected
        FirstFrame FirstFrameObject = new FirstFrame();
        this.dispose();
    }//GEN-LAST:event_backMenuMenuSelected

    private void onButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonActionPerformed
        // TODO add your handling code here:

        try {
            connectDB();
            statement = con.createStatement();
            String sql = "TRUNCATE screenshot";
            statement.executeUpdate(sql);

            statement = con.createStatement();
            sql = "INSERT INTO `shopping_mall_database`.`screenshot` (`status`) VALUES  ('1')";
            statement.executeUpdate(sql);
            this.dispose();
            new Setting();
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_onButtonActionPerformed

    private void offButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offButtonActionPerformed
        try {
            connectDB();
            statement = con.createStatement();
            String sql = "TRUNCATE screenshot";
            statement.executeUpdate(sql);

            statement = con.createStatement();
            sql = "INSERT INTO `shopping_mall_database`.`screenshot` (`status`) VALUES  ('0')";
            statement.executeUpdate(sql);
            this.dispose();
            new Setting();
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_offButtonActionPerformed

    private void backupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupButtonActionPerformed

        Process p = null;
        try {
            Runtime runtime = Runtime.getRuntime();
            p = runtime.exec("C:/xampp/mysql/bin/mysqldump.exe -uroot --add-drop-database -B shopping_mall_database -r " + "Backup/" + "BACKUP" + ".sql");
//change the dbpass and dbname with your dbpass and dbname
            System.out.println("process start");
            int processComplete = p.waitFor();
            System.out.println("process ends");
            if (processComplete == 0) {

                System.out.println("Backup created successfully!");
                JOptionPane.showMessageDialog(this,"Backup Done Successfull in sql format at Backup Folder");

            } else {
                // lblMessage.setText("Could not create the backup");
                System.out.println("Could not create the backup");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_backupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewUserButton;
    private javax.swing.JMenu backMenu;
    private javax.swing.JButton backupButton;
    private javax.swing.JButton changeUsernamePasswordButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton offButton;
    private javax.swing.JButton onButton;
    // End of variables declaration//GEN-END:variables
}
